---
title: "Vis I"
author: "Kate Colvin"
date: "2024-09-26"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggridges)

```

```{r}

weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = case_match(
      id, 
      "USW00094728" ~ "CentralPark_NY", 
      "USW00022534" ~ "Molokai_HI",
      "USS0023B17S" ~ "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())

```

```{r}

ggplot(weather_df, aes(x = tmin, y = tmax)) +
  geom_point(aes(color = name), alpha = .5) + 
  geom_smooth(se = FALSE)

```

```{r}

ggplot(weather_df, aes(x = tmin, y = tmax, color = name)) + 
  geom_point(aes(size = prcp), alpha = .5) +
  geom_smooth(se = FALSE) + 
  facet_grid(. ~ name)

```

```{r}

ggplot(weather_df, aes(x = date, y = tmax, color = name)) + 
  geom_smooth(se = FALSE) 

```

```{r}

ggplot(weather_df, aes(x = tmin, fill = name)) + 
  geom_histogram()

```

```{r}

ggplot(weather_df, aes(x = tmin, fill = name)) + 
  geom_density(alpha = .5)

```

```{r}

ggplot(weather_df, aes(x = name, y = tmin)) + 
  geom_violin(aes(fill = name), alpha = .5) + 
  stat_summary(fun = "median", color = "blue")

```

# Ridge Plot

```{r}

weather_df %>% 
  ggplot(aes(x=tmin, y=name)) +
  geom_density_ridges()

```

LA univariate plots 

```{r}

weather_df %>% 
  ggplot(aes(x=prcp, fill = name)) +
  geom_density(alpha = 0.3)

weather_df %>% 
  ggplot(aes(x=name, y = prcp)) +
  geom_boxplot()

```

## Saving and embedding plots 

```{r}

ggp_weather <- weather_df %>% 
  ggplot(aes(x=date, y=tmax, color=name)) +
  geom_point()

ggsave("plots/ggp_weather.pdf", ggp_weather, width = 8, height = 5)

```

